name: Build Arm64 APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_apk_arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/free_up_space
      - uses: subosito/flutter-action@v2
        with:
          flutter-version-file: .tool_versions.yaml
          cache: true
      - uses: dtolnay/rust-toolchain@stable
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}-
      - run: ./scripts/add-firebase-messaging.sh
      - name: Build Debug Arm64 APK
        run: flutter build apk --debug --target-platform android-arm64
      - name: Upload Arm64 APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: fluffychat-whatsapp-arm64-debug
          path: build/app/outputs/flutter-apk/app-debug.apk
